# Generated by Django 4.2 on 2023-04-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='Name',
        ),
    ]
