# Generated by Django 4.2 on 2023-04-27 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_books', '0002_book_rename_name_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_books.author'),
        ),
    ]
