# Generated by Django 4.2 on 2023-04-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_books', '0003_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Author',
        ),
    ]
