# Generated by Django 4.2 on 2023-04-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_books', '0007_rename_published_date_book_published_date_book_copy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Copy',
            new_name='BookCopy',
        ),
    ]
