# Generated by Django 4.2 on 2023-04-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_books', '0008_rename_book_copy_bookcopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='ISBN',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
