# Generated by Django 4.2 on 2023-04-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_books', '0009_bookcopy_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='Available',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='Condition',
            field=models.CharField(choices=[('G', 'Good'), ('F', 'Fair'), ('P', 'Poor')], max_length=10, null=True),
        ),
    ]
