# Generated by Django 4.2 on 2023-04-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_books', '0010_bookcopy_available_bookcopy_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='ISBN',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
