# Generated by Django 4.2 on 2023-04-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_books', '0011_alter_bookcopy_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['Name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-Published_date']},
        ),
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'ordering': ['ISBN']},
        ),
    ]
