# Generated by Django 4.2 on 2023-04-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_books', '0012_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='bookcopy',
            name='Book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookCopy',
        ),
    ]
