# Generated by Django 4.2 on 2023-04-27 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_books', '0013_remove_book_author_remove_bookcopy_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Published_date', models.DateField(null=True)),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_books.author')),
            ],
            options={
                'ordering': ['-Published_date'],
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=17, null=True)),
                ('Condition', models.CharField(choices=[('G', 'Good'), ('F', 'Fair'), ('P', 'Poor')], max_length=10, null=True)),
                ('Available', models.BooleanField(default=True, null=True)),
                ('Book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_books.book')),
            ],
            options={
                'ordering': ['ISBN'],
            },
        ),
    ]
