# Generated by Django 4.2 on 2023-04-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_books', '0016_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['Name'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-Published_date'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'ordering': ['ISBN'], 'verbose_name': 'Copy of a Book', 'verbose_name_plural': 'Copies of Books'},
        ),
    ]
